name: Node.js CI with Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Node.js versions

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci  # Clean install dependencies
    - run: npm run build --if-present  # Build React app

    - name: Set Git identity
      run: |
        git config --global user.email "arabhishek101@gmail.com"  # Replace with your email
        git config --global user.name "abhipalit3"  # Replace with your GitHub username

    - name: Deploy to GitHub Pages
      run: npm run deploy  # Deploy using gh-pages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
